from setuptools import setup, find_packages

setup(
  name = 'deep_robotics_retarget',
  packages = find_packages(),
  author="deep-robotics",
  author_email="",
  description="retargeting for humanoid robots",
  url="https://github.com/DeepRoboticsLab/deep-robotics-retarget",
  license="MIT",
  version="0.2.0",
  install_requires=[
    "loop_rate_limiters",
    "mink",
    "mujoco",
    "numpy>=1.26.0,<2.0",
    # Match the PyTorch versions used by deep-robotics-mimic.
    "torch==2.7.0",
    "torchvision==0.22.0",
    "torchaudio==2.7.0",
    "scipy",
    "qpsolvers[proxqp]",
    "rich",
    "tqdm",
    "opencv-python==4.11.0.86",
    "natsort",
    "psutil",
    "smplx @ git+https://github.com/vchoutas/smplx",
    "protobuf",
    "redis[hiredis]",
    "imageio[ffmpeg]",
    "matplotlib",
  ],
  python_requires='>=3.11,<3.12',
)
